import type { Metadata } from 'next'
import { Montserrat, Open_Sans } from 'next/font/google'

import '../globals.css'

import { Header } from '@/components/Header'

const montserrat = Montserrat({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-montserrat',
})

const openSans = Open_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-open-sans',
})

export const metadata: Metadata = {
  title: 'Landing Page v2',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="antialiased">
      <body className={`${montserrat.variable} ${openSans.variable} md:text-xl bg-sky-100`}>
        <Header />
        <main className="mt-[66px] md:mt-[82px] min-h-[calc(100dvh-66px)] md:min-h-[calc(100dvh-82px)] flex px-4 lg:max-w-7xl lg:mx-auto text-slate-950">
          {children}
        </main>
      </body>
    </html>
  )
}
