import type { Metadata } from 'next'
import { Montserrat, Open_Sans } from 'next/font/google'

import './globals.css'

import { Header } from '@/components/Header'

const montserrat = Montserrat({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-montserrat',
})

const openSans = Open_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-open-sans',
})

export const metadata: Metadata = {
  title: 'Landing Page v2',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="antialiased">
      <body className={`${montserrat.variable} ${openSans.variable}`}>
        <Header />
        <main className="min-h-screen flex px-4">{children}</main>
      </body>
    </html>
  )
}
