import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import './globals.css'

import { Header } from '@/components/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Landing Page v2',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="antialiased">
      <body className={inter.className}>
        <Header />
        {/* testar pt apos o title */}
        <main className="min-h-screen px-4 pb-6 pt-[90px] text-sm">{children}</main>
      </body>
    </html>
  )
}
